# Generated by Django 5.1.1 on 2025-01-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchdata",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
