# Generated by Django 5.1.1 on 2024-10-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Calendar Project', 'verbose_name_plural': 'Calendar Projects'},
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Project Owner'), ('manager', 'Project Manager'), ('member', 'Team Member'), ('viewer', 'Viewer'), ('outreach', 'Team Outreach')], default='member', max_length=20),
        ),
    ]
