# Generated by Django 5.1.1 on 2024-11-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_event_options_alter_projectmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="public_project",
            field=models.BooleanField(default=False),
        ),
    ]
