# Generated by Django 5.1.1 on 2024-11-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_project_public_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="code",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique 6-character task identifier",
                max_length=6,
                unique=True,
            ),
        ),
    ]
