# Generated by Django 5.1.1 on 2024-11-08 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasebackup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='database_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
