# Generated by Django 5.1.1 on 2025-01-27 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0002_supportassistance_supportrequest_supportcomment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#FF0000", max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="priority_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="satisfaction_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tools.supporttag"),
        ),
    ]
