# Generated by Django 5.1.1 on 2024-11-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_videocontent_videonote'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='transcript_json_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='transcript_srt_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='transcript_txt_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='transcript_vtt_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
