# Generated by Django 5.1.1 on 2024-10-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_documentproof_posallocation_posexpense_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='total_amount',
            new_name='initial_amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='additional_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
