# Generated by Django 5.1.1 on 2024-10-23 04:18

import app.finance.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_total_amount_budget_initial_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='budget',
            name='additional_amount',
            field=app.finance.models.MoneyField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='initial_amount',
            field=app.finance.models.MoneyField(),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='amount',
            field=app.finance.models.MoneyField(),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount',
            field=app.finance.models.MoneyField(),
        ),
        migrations.AlterField(
            model_name='grantexpense',
            name='amount',
            field=app.finance.models.MoneyField(),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='amount',
            field=app.finance.models.MoneyField(),
        ),
        migrations.AlterField(
            model_name='posallocation',
            name='amount',
            field=app.finance.models.MoneyField(),
        ),
        migrations.AlterField(
            model_name='posexpense',
            name='amount',
            field=app.finance.models.MoneyField(),
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='grant',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='grantexpense',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='posallocation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='posexpense',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.currency'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_rates', to='finance.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rates', to='finance.currency')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
    ]
