# Generated by Django 5.1.1 on 2024-10-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_budget_options_alter_budgetallocation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='budgetallocation',
            name='currency',
        ),
    ]
