# Generated by Django 5.1.1 on 2024-10-11 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0003_option_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(limit_choices_to={'category': '1'}, on_delete=django.db.models.deletion.CASCADE, to='config.option')),
                ('status', models.ForeignKey(limit_choices_to={'category': '2'}, on_delete=django.db.models.deletion.CASCADE, related_name='asset_status', to='config.option')),
            ],
        ),
    ]
