# Generated by Django 5.1.1 on 2025-01-26 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="config.option"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_status",
                to="config.option",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="maintenance_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_type",
                to="config.option",
            ),
        ),
    ]
