# Generated by Django 5.1.1 on 2024-10-15 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetlifecycle',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_records', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='compliance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='depreciation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(limit_choices_to={'category': '3'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_type', to='config.option'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_records', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.supplier'),
        ),
    ]
