# Generated by Django 5.1.1 on 2024-10-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_supplier_alter_asset_options_asset_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlifecycle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/lifecycle/'),
        ),
    ]
