# Generated by Django 5.1.1 on 2024-12-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_remove_ticket_ticket_type_remove_ticket_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="register",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
