# Generated by Django 5.1.1 on 2024-12-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="writer",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="writer",
            name="person",
        ),
        migrations.AddField(
            model_name="person",
            name="organization",
            field=models.ManyToManyField(
                blank=True,
                related_name="people",
                to="people.organization",
                verbose_name="organization",
            ),
        ),
        migrations.DeleteModel(
            name="Speaker",
        ),
        migrations.DeleteModel(
            name="Writer",
        ),
    ]
