# Generated by Django 5.1.1 on 2024-10-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_backupzip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
