# Generated by Django 5.1.1 on 2024-10-09 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_speaker_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.organization'),
        ),
        migrations.AddField(
            model_name='writer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.organization'),
        ),
    ]
