# Generated by Django 5.1.1 on 2025-01-27 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
        ("people", "0003_person_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="category",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"Category": 5},
                on_delete=django.db.models.deletion.CASCADE,
                to="config.option",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
