# Generated by Django 5.1.1 on 2024-10-22 08:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_customuser_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('zip_file', models.FileField(upload_to='photo_backups/')),
                ('total_photos', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo Backup',
                'verbose_name_plural': 'Photo Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BackupZip',
        ),
    ]
