# Generated by Django 5.1.1 on 2025-01-27 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
        ("people", "0004_staff_category_staff_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="category",
            field=models.ForeignKey(
                limit_choices_to={"category": 5},
                on_delete=django.db.models.deletion.CASCADE,
                to="config.option",
            ),
        ),
    ]
