# Generated by Django 5.1.1 on 2025-01-30 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_alter_staff_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="department",
            new_name="departments",
        ),
    ]
