# Generated by Django 5.1.1 on 2025-01-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
        ("people", "0006_rename_department_staff_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="department",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"category": 6},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="config.option",
            ),
            preserve_default=False,
        ),
    ]
