# Generated by Django 5.1.1 on 2025-01-30 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0007_staff_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="departments",
        ),
    ]
