# Generated by Django 5.1.1 on 2024-10-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_photo_filename_alter_photo_google_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='google_refresh_token',
            new_name='oauth_refresh_token',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='google_token',
            new_name='oauth_token',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='google_token_expiry',
            new_name='oauth_token_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_provider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
