# Generated by Django 5.1.1 on 2024-10-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobackup',
            name='photos_limit',
            field=models.IntegerField(default=0, help_text='Number of photos to backup (0 for unlimited)'),
        ),
    ]
