# Generated by Django 5.1.1 on 2024-10-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_photobackup_photos_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobackup',
            name='photos_limit',
            field=models.IntegerField(default=50, help_text='Number of photos to backup (0 for unlimited)'),
        ),
    ]
