# Generated by Django 5.1.1 on 2024-10-26 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_photobackup_photos_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobackup',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photobackup',
            name='photos_limit',
            field=models.IntegerField(default=0),
        ),
    ]
