# Generated by Django 5.1.1 on 2024-12-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_remove_writer_organization_remove_writer_person_and_more"),
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="partners",
            field=models.ManyToManyField(
                blank=True, related_name="partnered_publications", to="people.person"
            ),
        ),
    ]
