# Generated by Django 5.1.1 on 2025-01-09 07:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0002_alter_publication_partners"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_views", models.PositiveIntegerField(default=0)),
                ("daily_downloads", models.PositiveIntegerField(default=0)),
                ("last_daily_update", models.DateTimeField(null=True)),
                ("weekly_views", models.PositiveIntegerField(default=0)),
                ("weekly_downloads", models.PositiveIntegerField(default=0)),
                ("last_weekly_update", models.DateTimeField(null=True)),
                ("monthly_views", models.PositiveIntegerField(default=0)),
                ("monthly_downloads", models.PositiveIntegerField(default=0)),
                ("last_monthly_update", models.DateTimeField(null=True)),
                (
                    "publication",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="publications.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationTrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("download", "Download"), ("view", "View")],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="publications.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publication_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["publication", "event_type", "timestamp"],
                        name="publication_publica_f5786e_idx",
                    )
                ],
            },
        ),
    ]
